### ISSUE TITLE
HTTPS解密, 握手失败: remote error: tls: unknown certificate

### ISSUE THREAD

**Issue by nifflin** [ouqiang/mars#2]
```[app]
host = "0.0.0.0"
proxyPort = 8888
inspectorPort = 9999


[mitmProxy]
# 是否开启中间人代理， 不开启则盲转发
enabled = true
# 是否解密HTTPS, 客户端系统需安装根证书
decryptHTTPS = true
# 证书缓存大小
certCacheSize = 1000
# 数据缓存大小
leveldbCacheSize = 1000
```

系统macOS
go-mitt-proxy证书已安装到钥匙串-系统，但是系统在证书信息上显示“此证书不被信任”。mars server -c conf/app.toml
后台日志一直显示类似：
ERRO[0351] github.com:443 - HTTPS解密, 握手失败: remote error: tls: unknown certificate

**Comment by ouqiang** [comment]
https://github.com/ouqiang/goproxy/issues/5

**Comment by henson** [comment]
握手失败，证书已成功导入
<img width="388" alt="20200328_110125" src="https://user-images.githubusercontent.com/124816/77813431-8b966d80-70e3-11ea-9cc6-10a0e9fbd5bb.png">

OS：win7 64bit

INFO[0000]
   Version: v1.0.0
Go Version: go1.11
Git Commit: e92656e
     Built: 2019-01-04 23:05:43
   OS/ARCH: windows/amd64
INFO[0000] Proxy server listen on 0.0.0.0:8888
INFO[0000] Inspector server listen on 0.0.0.0:9999
ERRO[0108] example.com:443 - HTTPS解密, 握手失败: remote error: tls: unknown certificate authority

**Comment by ouqiang** [comment]
不支持自签名证书

**Comment by henson** [comment]
那怎么解决？

**Comment by ouqiang** [comment]
可以修改源码，去掉证书校验
